variables_a_exclure <- c("SpGite", "SpALAN_L", "SpAltiM", "SpAltiL", "SpPenM", "SpPenL", "Splat", "Splon")
# "SpAltiS",
variables_indisp <- c(
  "SpBioC1", "SpBioC10", "SpBioC11", "SpBioC12", "SpBioC13", "SpBioC14", "SpBioC15",
  "SpBioC16", "SpBioC17", "SpBioC18", "SpBioC19", "SpBioC2", "SpBioC3", "SpBioC4", "SpBioC5",
  "SpBioC6", "SpBioC7", "SpBioC8", "SpBioC9", "SpWD", "SpWDp", "SpHOCS2M", "SpHOCS3M", "SpHOCS4M",
  "SpHOCS6M", "SpHOCS7M", "SpHOCS9M", "SpHOCS1M", "SpHOCS5M", "SpHOCS0M", "SpHOCS8M", "SpRo3M",
  "SpRo5L", "SpRo_dist"
)

variables_acp <- c(
  "SpALAN_M",
  "SpBioC1",
  "SpBioC10",
  "SpBioC11",
  "SpBioC12",
  "SpBioC13",
  "SpBioC14",
  "SpBioC15",
  "SpBioC16",
  "SpBioC17",
  "SpBioC18",
  "SpBioC19",
  "SpBioC2",
  "SpBioC3",
  "SpBioC4",
  "SpBioC5",
  "SpBioC6",
  "SpBioC7",
  "SpBioC8",
  "SpBioC9",
  "SpEasL",
  "SpEasM",
  "SpGro_L",
  "SpGro_M",
  "SpHOCS0M",
  "SpHOCS10M",
  "SpHOCS11M",
  "SpHOCS12M",
  "SpHOCS13M",
  "SpHOCS14M",
  "SpHOCS15M",
  "SpHOCS16M",
  "SpHOCS17M",
  "SpHOCS18M",
  "SpHOCS19M",
  "SpHOCS1M",
  "SpHOCS20M",
  "SpHOCS21M",
  "SpHOCS22M",
  "SpHOCS23M",
  "SpHOCS24M",
  "SpHOCS2M",
  "SpHOCS3M",
  "SpHOCS4M",
  "SpHOCS5M",
  "SpHOCS6M",
  "SpHOCS7M",
  "SpHOCS8M",
  "SpHOCS9M",
  "SpNorL",
  "SpNorM",
  "SpPenS",
  "SpPenM",
  "SpPenL",
  "SpRo5L",
  "SpRoAddM",
  "SpSumL",
  "SpSumM",
  "SpVCF_L",
  "SpVCF_M",
  "SpWD",
  "SpWDp"
)

variables_bio <- c(
  "SpALAN_M",
  "SpBioC1",
  "SpBioC10",
  "SpBioC11",
  "SpBioC12",
  "SpBioC13",
  "SpBioC14",
  "SpBioC15",
  "SpBioC16",
  "SpBioC17",
  "SpBioC18",
  "SpBioC19",
  "SpBioC2",
  "SpBioC3",
  "SpBioC4",
  "SpBioC5",
  "SpBioC6",
  "SpBioC7",
  "SpBioC8",
  "SpBioC9"
)
vars_norm <- c("SpRo_dist", "Spprecipitations", "Sptemp", "Spwind")
